repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: \.(py|txt|ipynb)$
      - id: end-of-file-fixer
        files: \.(py|txt|ipynb)$

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: \.(py|ipynb)$  # Black only supports Python and Jupyter

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
        args: [--fix]  # 🧠 enable autofix
        files: \.(py|ipynb)$